import { useRouter } from "next/router";
import { MEASURES } from "../constants/measures";
import {
  bgColor,
  brandingAccent,
  brandingDark,
  brandingLight,
  brandingNeutral,
  brandingNeutralLight,
  brandingNeutralStrong,
  fontFamilyMain,
  fontFamilySecondary,
  textColor,
} from "../styles/globalstyles";

export const dark = {
  colors: {
    dark: brandingDark,
    light: brandingLight,
    accent: brandingAccent,
    neutral: brandingNeutral,
    neutralStrong: brandingNeutralStrong,
    neutralLight: brandingNeutralLight,
    black: "#000000",
    darker: "#281E30",
    white: "#ffffff",
    text: brandingLight,
    textSecond: "#281E30",
    textNeutral: "#91A09F",
    inverseText: brandingDark,
    // background: "#3A323D",
    background: "#281E30",
    lightBackground: "#D8E8E7",
    backgroundWhite: "#FFF",
    backgroundCard: brandingLight,
    danger: "orangered",
    success: "#00FF85",
    grey900: "#29282C",
    grey800: "#414044",
    grey700: "#58585B",
    grey600: "#707073",
    grey500: "#88878A",
    grey400: "#A09FA1",
    grey300: "#B8B7B9",
    grey200: "#CFCFD0",
    grey100: "#E7E7E8",
    grey50: "#F3F3F3",
    grey20: "#FAFAFA",
    grey10: "#FDFDFD",
  },
  fontSizes: {
    huge: "48px",
    big: "29px",
    medium: "22px",
    small: "16px",
    tiny: "14px",
  },
  fontWeights: {
    black: 900, // just a convention from the font itself (black = strongest)
    bold: 700,
    regular: 400,
    extraLight: 200,
  },
  measures: {
    big: `${MEASURES.big}px`,
    medium: `${MEASURES.medium}px`,
    small: `${MEASURES.small}px`,
    tiny: `${MEASURES.tiny}px`,
  },
  fontFamilies: {
    main: fontFamilyMain,
    secondary: fontFamilySecondary,
  },
};
